### ISSUE TITLE
How do I set up the app locally

### ISSUE THREAD

**Issue by singh-yashwant** [vector-sih/pbs2#3]
Can someone upload the details on how to run the app locally

**Comment by Aditya-Sihmar** [comment]
Use the instructions in the file which was forwarded to the group (Flock). There might come some errors ask @sauravrajleaf or any other development team member they will help you resolve the issues. I will update the readme file soon so that those instructions are clear.

**Comment by singh-yashwant** [comment]
Yeah thanks
